% Extracting the results from the LeggedRobotSim3D file


i = out.currentKnee.Data; % The current generated by the PD controller so
% that the model matches the desired gait generation
t = out.currentKnee.Time;

C_zCoords = out.C_z.Data; % The z-Coordinate of the movement of the leg
% from its mechanics and the PD controller
omega = out.omega_actKnee.Data; % The angle offset of the knee joint from
% movement of the leg as a result of its mechanics and the PD controller

% From the Spatial Contact Force block:

time = out.contact.Time;
contactSignal = out.contact.Data;
penetrationDepth = out.d.Data;
normalForceMag = out.nfm.Data;

plot(t, omega)


