% Extracting the results from the LeggedRobotSim2D file

theta_2 = out.theta_2.Data; % The gait generated used in the PD controller
theta_2Time = out.theta_2.Time;

figure(1)
plot(theta_2Time, theta_2)
title('Gait Generated Angle Offsets over Time (Simulink)')
legend('Knee Joint')
xlabel('Time (s)')
ylabel('Angle (radians)')
grid on

C_zCoords = out.C_z.Data; % The z-Coordinate of the movement of the leg
% from its mechanics and the PD controller
C_zt = out.C_z.Time;

omega = out.omega_actKnee.Data; % The angle offset of the knee joint from
% movement of the leg as a result of its mechanics and the PD controller
omegat = out.omega_actKnee.Time;

figure(2)
subplot(2, 1, 1)
plot(C_zt, C_zCoords)
title('Measured z-Coordinate of Foot over Time')
xlabel('Time (s)')
ylabel('z Position (m)')

subplot(2, 1, 2)
plot(omegat, omega)
title('Measured Angular Velocity over Time')
legend('Knee Joint')
ylabel('Angular Velocity (m/s)')
xlabel('Time (s)')
grid on

i = out.currentKnee.Data; % The current generated by the PD controller so
% that the model matches the desired gait generation
it = out.currentKnee.Time;

figure(3)
plot(it, i)
title('Current Generated by PD Controller')
xlabel('Time (s)')
ylabel('Current (A)')
grid on


