% Extracting the results from the leggedRobotSim2D file

%theta_2 = out.theta_2.Data; % The gait generated used in the PD controller
%theta_2Time = out.theta_2.Time;
%
%figure(1)
%plot(theta_2Time, theta_2)
%title('Gait Generated Angle Offsets over Time (Simulink)')
%legend('Knee Joint')
%xlabel('Time (s)')
%ylabel('Angle (radians)')
%grid on

C_zCoords = out.C_z2D.Data; % The z-Coordinate of the movement of the leg
% from its mechanics and the PD controller
t = out.C_z2D.Time;

omega = out.omega_actKnee2D.Data; % The angle offset of the knee joint from
% movement of the leg as a result of its mechanics and the PD controller
%omegat = out.omega_actKnee.Time;

i = out.currentKnee2D.Data; % The current generated by the PD controller so
% that the model matches the desired gait generation
%it = out.currentKnee.Time;

% Saving the results for model verification
save('simulinkResults.mat', 't', 'C_zCoords', 'omega', 'i');

figure(1)
subplot(3, 1, 1)
plot(t, C_zCoords)
title('Measured z-Coordinate of Foot over Time (Simulink)')
xlabel('Time (s)')
ylabel('z Position (m)')
grid on

subplot(3, 1, 2)
plot(t, omega)
title('Measured Angular Velocity over Time (Simulink)')
legend('Knee Joint')
ylabel('Angular Velocity (rad/s)')
xlabel('Time (s)')
grid on

subplot(3, 1, 3)
plot(t, i)
title('PD Controller Output - i(t) (Simulink)')
xlabel('Time (s)')
ylabel('Current (A)')
grid on


